### ISSUE TITLE
Installation broken on Mac/Linux

### ISSUE THREAD

**Issue by rke** [virtual-world-framework/vwf#414]
The current install.sh script contains this line:
VERSION=$(cat support/client/lib/version.js | support/deployment/version.sh)
which assumes that the working directory when running the suggested installation command:
curl -kL http://get.virtual.wf  | sh
does contains a file ./support/client/lib/version.js.
This is very unlikely unless the installation is run from a directory where vwf is already checked out.
I was just trying a first time install and don't have any experience with the code base so I can't propose a fix, but though I let you know at least.
Best Regards,
Rainer Keller

**Comment by allisoncorey** [comment]
Thanks for letting us know @rke. We will look into this asap this week!

**Comment by allisoncorey** [comment]
@rke The installation script has been updated to pull the latest version from our downloads server, rather than relying on a version number from version.js. Please let us know if this resolves your issue, as well as any other feedback you might have!

**Comment by rke** [comment]
Thanks Allison, I had a successfull install now!
