### ISSUE TITLE
Cesium demo problem

### ISSUE THREAD

**Issue by lazydino** [virtual-world-framework/vwf#415]
Hi,

Anyone tried cesium demo? It seems run fine with 'localhost:3000/public/agi/cesium', but will not load the globe if access demo remotely via other machine with its NIC IP '192.168.1.199:3000/public/agi/cesium'. Chrome console shows 'Load timeout for modules:' for a bunch of vwf components like  vwf/model/cesium/core/Transforms, vwf/model/cesium.....

It does not look like a browser caches issue.  Any idea why this happened?

**Comment by scottnc27603** [comment]
@lazydino 

Can you try loading: http://demo.virtual.wf/agi/cesium/

**Comment by lazydino** [comment]
It runs fine now. Where can I pull and test the update code?

**Comment by scottnc27603** [comment]
Does https://demo.virtual.wf/agi/cesium/ load?

**Comment by scottnc27603** [comment]
@lazydino 
I've updated to the latest version of Cesium, so you should try out that branch to see if that fixes any of the issues you've been seeing.

**Comment by lazydino** [comment]
Is the demo site down? I can't access demo.virtual.wf....

**Comment by davideaster** [comment]
The SSL server was down this morning, but the site is up now.

**Comment by scottnc27603** [comment]
Our Cesium support has been updated to version 1.5.  I don't think that anything has changed as far as loading, but you might want to test the cesium app again.  Please note that most all of the applications have been moved into a separate repo.  

https://github.com/virtual-world-framework/vwf-apps
