### ISSUE TITLE
Current Issues on Development

### ISSUE THREAD

**Issue by allisoncorey** [virtual-world-framework/vwf#462]
In preparation for 0.7.0 release, the following issues on development need to be addressed:

- [x] adl/assetCache - does not properly replicate (legacy issue?)
- [x] **adl/assetCacheMaterial** - the second object's material is not shown. Appears to have been created on modern ID merge. 
- [x] agi/test/polygon - errors on second client join (cannot read property length of undefined). 
- [x] **marbles** - There are no marbles on the selection or solitaire table. Perhaps related to the component relative resources change? The model's source is defined in the component script. 
- [x] **humvee-lesson and radio-lesson** - not properly working with the component relative resources change
- [x] **radio** - body texture only loads the first time on a fresh instance on a fresh server. Subsequent loads render solid black. 
- [x] sandtable - Drag and drop functionality does not work (legacy issue). 
- [x] **editor (sandtable)** - models tab does not populate
- [x] **editor (sandtable)** - save/load does not work on users tab. 
- [x] **solar-system** - width error in console, related to the stars component materialDefinition repeat. 
- [x] **stereo** - same width error as solar-system
- [x] **test/cameraFov, test/cameraNearFar, test/CamPosX, test/CamPosY, test/CamPosZ, test/childTransforms, test/clientNotification, test/future, test/keyStates, test/lookAt, test/mouseInput, test/mousePick, test/ObjPosX, test/ObjPosY, test/ObjPosZ, test/ObjQuat..., test/ObjRot..., test/visible**  -  the lighting on the second client is darker. Refreshing the first client uses the darker lighting. 
- [x] **test/cameraType** - box is black
- [x] **test/clientNotification** - no notification on client left
- [x] **test/JSONLoaderTest** - second client monster has solid black texture
- [x] **test/lightColor** - does not work
- [x] **test/physics** - cube has black texture
- [x] **test/point-light, test/pointlightPos...** - does not work
- [x] **test/texture** - does not replicate

Add to backlog:
- sandtable - predators jump every few frames (redmine #2868)
- test/createDelete - does not replicate. This actually is replicating, but the duck that is deleted from the first client during load remains in the second client. Add to redmine backlog. 
- Deprecated warning - Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
- Are particles supposed to replicate exactly?

**Comment by davideaster** [comment]
> body texture only loads the first time on a fresh instance on a fresh server

This is an issue with the file cache. As as test, commenting out lines 39-45 in `file-cache.js` disables the cache and fixes the problem.

    for ( var i = 0; i < this.files.length; i++ ) {
        if( this.files[ i ].path == path ) {    
            global.log( 'serving from cache: ' + path, 2 );
            callback( this.files[ i ] );
            return;
        }
    }

As of `branch/node-absolute-application-url` and `branch/component-relative-resources`, resources inside the application component are served directly from the component as `/path/to/component/resource.ext` instead of through the reflector instance at `/path/to/application/0123456789ABCDEF/resource.ext`. The direct paths go through the file cache, but the instance-relative paths do not.

I don't know what the cache is doing to break cached results. The content type or encoding may not be set correctly.

**Comment by scottnc27603** [comment]
solar-system and stereo are fixed with:
https://github.com/virtual-world-framework/vwf/pull/465

**Comment by allisoncorey** [comment]
#465 also appears to fix the following issues:

- adl/assetCacheMaterial 
- the black texture issue on subsequent loads of radio
- lighting issue with second clients
- test/lightColor 
- test/JSONLoaderTest 
- test/lightColor

:+1:

**Comment by davideaster** [comment]
The radio body texture problem is probably a race condition and not related to the cache per se. Even with the cache disabled, I get the black body texture sometimes. In one case, the radio consistently loads correctly when I have Chrome's Inspector window open and consistently loads with the black body texture when the Inspector is closed. Presumably the texture data isn't being handled correctly when the image loads too quickly. That would explain why the first, uncached load works, but the others don't.

**Comment by allisoncorey** [comment]
adl/assetCache issue resolved in https://github.com/virtual-world-framework/vwf-apps/pull/19

**Comment by allisoncorey** [comment]
sandtable drag and drop issue and editor save/load issue are solved in #468
